---
name: Lint

on:
  pull_request:
  push:
    branches:
      - 'master'

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v25
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - name: run lint scripts
      run: |
        for f in lint/lint_*.py; do
          if ! python $f; then
            echo "errors from $f ^^^^"
            exit 1
          fi
        done
